apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-ryheygzc
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-ryheygzc:bf791b9336b65e37724b166036ba77b98b8be4d7@sha256:90fbd91715d71c20988a902ecf33681db2210e9c0e022c9abff2a38452c0585c
        name: container-image  
